---
# Install Hadoop and Spark
# ==================

- hosts: all
  become: true
  vars:
    download_folder: /usr/local
    file: /usr/local/hadoop-2.7.3/etc/hadoop/hadoop-env.sh
    spark_conf: /usr/local/spark-2.1.0-bin-hadoop2.7/conf
    jpath: export JAVA_HOME=/usr/lib/jvm/default-java/jre/
    hpath: export HADOOP_CONF_DIR="/usr/local/hadoop-2.7.3/etc/hadoop/"
  tasks: 
  - name: install java
    apt: name=default-jdk state=present update_cache=yes

  - name: download Hadoop
    get_url:
      url: http://www-us.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz
      dest: "{{download_folder}}"
      
  - name: Unzip Hadoop
    unarchive: copy=no src={{download_folder}}/hadoop-2.7.3.tar.gz dest={{download_folder}}
    
  - name: Modify the Hadoop configuration
    lineinfile: dest="{{file}}" regexp="^{{jpath}}" line="{{jpath}}"

  # Install Spark
  - name: download Spark
    get_url:
      url: https://archive.apache.org/dist/spark/spark-2.1.0/spark-2.1.0-bin-hadoop2.7.tgz
      dest: "{{download_folder}}"
    
  - name: Unzip Spark
    unarchive: copy=no src={{download_folder}}/spark-2.1.0-bin-hadoop2.7.tgz dest={{download_folder}}
    
  - copy:
      src: "{{spark_conf}}/spark-env.sh.template"
      dest: "{{spark_conf}}/spark-env.sh"
      remote_src: true

  - name: Modify spark-env.sh configuration
    lineinfile: dest="{{spark_conf}}/spark-env.sh" regexp="^{{hpath}}" line="{{hpath}}"
